// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RushTodo.Data;

namespace RushTodo.Data.Migrations
{
    [DbContext(typeof(TodoItemDbContext))]
    partial class TodoItemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JKang.EventSourcing.Persistence.EfCore.EventEntity<System.Guid>", b =>
                {
                    b.Property<Guid>("AggregateId");

                    b.Property<int>("AggregateVersion");

                    b.Property<string>("Serialized");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("AggregateId", "AggregateVersion");

                    b.ToTable("TodoItemEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
